### ISSUE TITLE
Algoritmo errato per cognomi con 3 o più consonanti

### ISSUE THREAD

**Issue by ugol** [squeeze69/generacodicefiscale#1]
"Se il cognome contiene tre o più consonanti, i tre caratteri da rilevare sono, nell'ordine, la prima, la seconda e la terza consonante."

con LANDINI, il mio cognome, rileva invece prima terza e quarta.

volevo inserire la tua libreria nel mio generatore di dati casuali https://github.com/ugol/jr

**Comment by squeeze69** [comment]
Grazie, in effetti, sbagliando, usavo lo stesso "algoritmo" per cognome e nome, una leggerezza non da poco.
Ho corretto il problema ed aggiunto dei test (fra cui ho usato il tuo cognome, per andare sul sicuro), l'ho passata a v1.0.3
